project:
  type: website
  output-dir: docs

website:
  title: Haejin Kim
  navbar:
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - posts.qmd
      - href: docs/HK_resume_f.pdf
        text: cv
      - icon: github
        href: https://github.com/samanthacsik/samanthacsik.github.io
      - icon: linkedin
        href: https://www.linkedin.com/in/samanthacsik/
      - icon: envelope
        href: mailto:scsik@ucsb.edu

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full
    sidebar: false

editor: visual


